# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lcXXJn3-I6lJXoM_JZntZeh3B8T230Zp
"""

import random as rd
import matplotlib.pyplot as plt
import numpy as np

size_siml = 1000000
terminal_data = [1, 2, 3]
# The above array is an array of integers, 1 representing the event of choosing the first terminal, 2 representing the event of choosing the second terminal,
# 3 representing the event of choosing the third terminal.
numb_same = numb_different = 0
#The above variables are going to store the number of iterations where same terminal is chosen and number of iterations where different terminal is chosen respectively. 
#The for loop goes through 1000000 iterations. 
for i in range(size_siml):
  sim_itr_1 = rd.randint(0, 2)
  sim_itr_2 = rd.randint(0, 2)
  if(sim_itr_1 == sim_itr_2):
    numb_same += 1
  else:
    numb_different += 1
  
  
# The variables below store the probability values based on simulations  
prob_same = numb_same / size_siml
prob_differ = numb_different / size_siml
#Creating an array to store the probabilities
probabilities_simu = [prob_same, prob_differ]

print(" The following results are obtained from simulations")
print(f"(b) Choosing different terminals has a probability of : {probabilities_simu[1]}")

print()
print("The following results are obtained theoretically")
print("(b) Choosing different terminals has a probability of : 0.6667")
diff_var_diff = probabilities_simu[1] - 0.6667
print(f"The difference between the simulations' and the theoretical values are : {diff_var_diff}")